### ISSUE TITLE
自己写 3.1 案例播放失败

### ISSUE THREAD

**Issue by HuaiGuangPan** [yangchong211/YCVideoPlayer#100]
跟着做 3.1 的实例（代码全复制， NormalActivity 以及涉及到的其他类），点击播放后播放器页面转了很久（加载），然后显示“视频播放异常” 
![Uploading 加载中.jpg…]()
![播放异常](https://user-images.githubusercontent.com/48399927/112320095-aa751300-8ce9-11eb-8aac-1a2d1f3c7bb4.jpg)

异常信息：
`W/MediaPlayer: Couldn't open http://vfx.mtime.cn/...
    java.io.FileNotFoundException: No content provider: http://vfx.mtime.cn/Video/2019/02/04/mp4/190204084208765161.mp4
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1692)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1522)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1439)
`

但是 Demo 在我手机上运行良好。

我尝试过：
1. 添加权限
2. 更换视频链接

但是问题还是没变。

**Comment by HuaiGuangPan** [comment]
之前也是在使用一个别的播放器库，自己写的代码也是播放不了。

我想可能是我自己的项目没有配置好什么东西😰 @yangchong211

**Comment by HuaiGuangPan** [comment]
问题找到了，是 AndroidManifest 文件中没有指定 application name 属性为 BaseApplication
