### ISSUE TITLE
在demo里直接 gradle compile 'cn.yc:YCVideoPlayerLib:2.2'  点击播放视频提示没有so

### ISSUE THREAD

**Issue by skill20** [yangchong211/YCVideoPlayer#13]
Process: com.aptdemo, PID: 15939
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.aptdemo-Ap8OdRzETtAcU2HGQOjDUQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.aptdemo-Ap8OdRzETtAcU2HGQOjDUQ==/lib/arm64, /data/app/com.aptdemo-Ap8OdRzETtAcU2HGQOjDUQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]] couldn't find "libijkffmpeg.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1660)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:178)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:189)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:230)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:226)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:217)
        at org.yczbj.ycvideoplayerlib.VideoPlayer.initMediaPlayer(VideoPlayer.java:518)
        at org.yczbj.ycvideoplayerlib.VideoPlayer.start(VideoPlayer.java:227)
        at org.yczbj.ycvideoplayerlib.VideoPlayerController.onClick(VideoPlayerController.java:566)
        at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by skill20** [comment]
有的机型有声音，没图像
