### ISSUE TITLE
在fragment中以recycleview形式点击报错

### ISSUE THREAD

**Issue by 748297973** [yangchong211/YCVideoPlayer#61]
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.movies.k8, PID: 6228
    java.lang.IllegalArgumentException: Illegal null AudioFocusRequest
        at android.media.AudioManager.abandonAudioFocusRequest(AudioManager.java:2969)
        at org.yczbj.ycvideoplayerlib.player.VideoPlayer.releasePlayer(VideoPlayer.java:1061)
        at org.yczbj.ycvideoplayerlib.player.VideoPlayer.release(VideoPlayer.java:1039)
        at org.yczbj.ycvideoplayerlib.manager.VideoPlayerManager.releaseVideoPlayer(VideoPlayerManager.java:94)
        at org.yczbj.ycvideoplayerlib.manager.VideoPlayerManager.setCurrentVideoPlayer(VideoPlayerManager.java:59)
        at org.yczbj.ycvideoplayerlib.player.VideoPlayer.start(VideoPlayer.java:379)
        at org.yczbj.ycvideoplayerlib.controller.VideoPlayerController.onClick(VideoPlayerController.java:886)
        at android.view.View.performClick(View.java:6712)
        at android.view.View.performClickInternal(View.java:6675)
        at android.view.View.access$3400(View.java:799)
        at android.view.View$PerformClick.run(View.java:26309)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7266)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:909)
I/Process: Sending signal. PID: 6228 SIG: 9
Process 6228 terminated.
`
只能点击一个item,再点击另外的就报上述错误,把mAudioManager.abandonAudioFocusRequest(null);注释后可以点击当前可视的列表视频,在播放的时候往下拉就会报cannot be cast to com.movies.k8.holder.VideoViewHolder类型不能强制转换

**Comment by yangchong211** [comment]
没发现这种错误，你可以在看一下demo，这个应该是recyclerView使用方法的问题，具体可以看看demo中案例代码
